// <auto-generated />
namespace MovieCustomerWithAuthMVC_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddReleaseDateAndNoInStockinMoviepococlass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReleaseDateAndNoInStockinMoviepococlass));
        
        string IMigrationMetadata.Id
        {
            get { return "202009021502330_ Add ReleaseDate And NoInStock in Movie poco class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
